#!/usr/bin/env node
/**
 * Bundle the cron worker (src/workers/cron.ts + its job modules) into a single
 * CommonJS file that ships with the Next.js standalone output.
 *
 * Output path: .next/standalone/apps/web/workers/cron.js
 * PM2 picks it up via ecosystem.config.js (frenzpay-worker process).
 *
 * We externalise everything Next's standalone tracing already bundles — Prisma,
 * native @node-rs/argon2, ioredis, our own workspace packages — so there's no
 * duplicate copy and no chance of two client instances.
 */

import { build } from 'esbuild';
import { mkdir, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const STANDALONE = resolve(repoRoot, '.next/standalone/apps/web');
const ENTRY = resolve(repoRoot, 'src/workers/cron.ts');
// ESM output (cron.ts uses top-level await). PM2 happily runs `node cron.mjs`.
// We emit as `.cjs`-extension-but-ESM by keeping `.js` and emitting a package.json
// sibling that flips the module type. Simpler: just use `.mjs`.
const OUTFILE = resolve(STANDALONE, 'workers/cron.mjs');

async function exists(p) {
  try { await access(p, constants.F_OK); return true; } catch { return false; }
}

if (!(await exists(STANDALONE))) {
  console.error(`[build-worker] Standalone dir not found: ${STANDALONE}`);
  console.error('[build-worker] Run `next build` first.');
  process.exit(1);
}

if (!(await exists(ENTRY))) {
  console.error(`[build-worker] Worker entry not found: ${ENTRY}`);
  process.exit(1);
}

await mkdir(dirname(OUTFILE), { recursive: true });

// External = resolved at runtime from the standalone node_modules. Anything NOT
// listed here gets inlined into the bundle.
//
// NB: Next standalone's node_modules tree uses pnpm's flat .pnpm/... layout
// with NO top-level symlinks for most packages. Inlining is safer than
// externalising for pure-JS modules. Only things with native bindings
// (Prisma engines, argon2) stay external — deploy.sh creates top-level
// symlinks for those.
const external = [
  // Prisma has a C++ engine binary loaded via path walking; keep its package
  // external so it picks up the engine from standalone/apps/web/.prisma/client
  // that deploy.sh rsyncs in. deploy.sh also maintains the top-level
  // node_modules/@prisma/client symlink so the require works from cron.mjs.
  '@prisma/client',
  '.prisma/client',
  // Native Rust binding
  '@node-rs/argon2',
];

const result = await build({
  entryPoints: [ENTRY],
  outfile: OUTFILE,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: 'linked',
  minify: false, // keep readable — this is a background process, perf ≠ size
  external,
  logLevel: 'info',
  // Node 22 supports `--enable-source-maps`; our ecosystem config passes it.
  banner: {
    js: '/* FrenzPay cron worker — generated by build-worker.mjs */',
  },
});

if (result.errors.length) {
  console.error('[build-worker] esbuild failed');
  process.exit(1);
}

console.log(`[build-worker] wrote ${OUTFILE}`);
