#!/usr/bin/env node
/**
 * Bundle the cron worker (src/workers/cron.ts + its job modules) into a single
 * CommonJS file that ships with the Next.js standalone output.
 *
 * Output path: .next/standalone/apps/web/workers/cron.js
 * PM2 picks it up via ecosystem.config.js (frenzpay-worker process).
 *
 * We externalise everything Next's standalone tracing already bundles — Prisma,
 * native @node-rs/argon2, ioredis, our own workspace packages — so there's no
 * duplicate copy and no chance of two client instances.
 */

import { build } from 'esbuild';
import { mkdir, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const STANDALONE = resolve(repoRoot, '.next/standalone/apps/web');
const ENTRY = resolve(repoRoot, 'src/workers/cron.ts');
const OUTFILE = resolve(STANDALONE, 'workers/cron.js');

async function exists(p) {
  try { await access(p, constants.F_OK); return true; } catch { return false; }
}

if (!(await exists(STANDALONE))) {
  console.error(`[build-worker] Standalone dir not found: ${STANDALONE}`);
  console.error('[build-worker] Run `next build` first.');
  process.exit(1);
}

if (!(await exists(ENTRY))) {
  console.error(`[build-worker] Worker entry not found: ${ENTRY}`);
  process.exit(1);
}

await mkdir(dirname(OUTFILE), { recursive: true });

// External = resolved at runtime from the standalone node_modules. Anything NOT
// listed here gets inlined into the bundle.
const external = [
  // Workspace packages — Next traces these into standalone/node_modules/...
  '@frenzpay/auth',
  '@frenzpay/db',
  '@frenzpay/events',
  '@frenzpay/kyc',
  '@frenzpay/ledger',
  '@frenzpay/logger',
  '@frenzpay/providers',
  '@frenzpay/validators',
  // Heavy / native deps best left unbundled
  '@prisma/client',
  '.prisma/client',
  '@node-rs/argon2',
  'ioredis',
  'node-cron',
  'nodemailer',
  'pino',
  'pino-pretty',
];

const result = await build({
  entryPoints: [ENTRY],
  outfile: OUTFILE,
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22',
  sourcemap: 'linked',
  minify: false, // keep readable — this is a background process, perf ≠ size
  external,
  logLevel: 'info',
  // Node 22 supports `--enable-source-maps`; our ecosystem config passes it.
  banner: {
    js: '/* FrenzPay cron worker — generated by build-worker.mjs */',
  },
});

if (result.errors.length) {
  console.error('[build-worker] esbuild failed');
  process.exit(1);
}

console.log(`[build-worker] wrote ${OUTFILE}`);
